# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form1(object):
    def setupUi(self, QWidget):
        QWidget.setObjectName("QWidget")
        QWidget.setGeometry(QtCore.QRect(0, 0, 735, 226))
        self.plainTextEdit = QtWidgets.QPlainTextEdit(QWidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(10, 10, 241, 71))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.pushButton = QtWidgets.QPushButton(QWidget)
        self.pushButton.setGeometry(QtCore.QRect(260, 30, 81, 31))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(QWidget)
        self.pushButton_2.setGeometry(QtCore.QRect(350, 30, 81, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(QWidget)
        self.pushButton_3.setGeometry(QtCore.QRect(440, 30, 81, 31))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(QWidget)
        self.pushButton_4.setGeometry(QtCore.QRect(530, 30, 81, 31))
        self.pushButton_4.setObjectName("pushButton_4")
        self.tableWidget = QtWidgets.QTableWidget(QWidget)
        self.tableWidget.setGeometry(QtCore.QRect(10, 80, 720, 192))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)

        self.retranslateUi(QWidget)
        QtCore.QMetaObject.connectSlotsByName(QWidget)

    def retranslateUi(self, Кофе):
        _translate = QtCore.QCoreApplication.translate
        Кофе.setWindowTitle(_translate("Form1", "Form"))
        self.pushButton.setText(_translate("Form1", "Запуск"))
        self.pushButton_2.setText(_translate("Form1", "Изменить"))
        self.pushButton_3.setText(_translate("Form1", "Добавить"))
        self.pushButton_4.setText(_translate("Form1", "Удалить"))
